version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application docker image
          command: |
            docker build -t database-broker .
      - run:
          name: Run tests
          command: |
            docker run database-broker make tests
          environment:
            DATABASE_URL: "postgres://root:root@localhost:5432/test"
            NAME_PREFIX: testing
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              if [ "${CIRCLE_PROJECT_USERNAME}" == "akkeris" ]; then 
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
                docker tag database-broker "docker.io/akkeris/database-broker:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                docker push "docker.io/akkeris/database-broker:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag database-broker "docker.io/akkeris/database-broker:release-${CIRCLE_BUILD_NUM}"
                  docker tag database-broker "docker.io/akkeris/database-broker:latest"
                  docker push "docker.io/akkeris/database-broker:latest"
                  docker push "docker.io/akkeris/database-broker:release-${CIRCLE_BUILD_NUM}"
                fi
              fi
            fi
